Fix: KuCoin fetch_ohlcv() in Python
Python does not allow you to implicitly cast strings to floats and ints. The math on line 506 therefore fails.

```
>>> ccxt.kucoin().fetch_ohlcv('ETH/BTC', limit=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/ccxt/kucoin.py", line 506, in fetch_ohlcv
    start = end - minutes * 60 * limit
TypeError: unsupported operand type(s) for -: 'int' and 'str'
```