feat(bitflyer): fetchFundingRate (#24049)
* feat(bitflyer): fetchFundingRate

* currencies/bitflyer.json trailing comma error

This error was kinda difficult to find because the error log doesn't mention the actual file that the error was index
This was the error log, it doesn't mention ts/src/test/static/currencies/bitflyer.json

```
INFO:MAIN] Exchange to test: bitflyer

file:///home/travis/build/ccxt/ccxt/js/src/test/tests.helpers.js:11

    throw new Error(exceptionMessage(e));

    ^

Error: [Error] Error: [SyntaxError] SyntaxError: Unexpected token } in JSON at position 4924

    at JSON.parse (<anonymous>)

    at ioFileRead (file:///home/travis/build/ccxt/ccxt/js/src/test/tests.helpers.js:75:26)

    at testMainClass.loadMarketsFromFile (file:///home/travis/build/ccxt/ccxt/js/src/test/tests.js:860:25)

    at testMainClass.initOfflineExchange (file:///home/travis/build/ccxt/ccxt/js/src/test/tests.js:1150:30)

    at testMainClass.testExchangeRequestStatically (file:///home/travis/build/ccxt/ccxt/js/src/test/tests.js:1158:31)

    at testMainClass.runStaticTests (file:///home/travis/build/ccxt/ccxt/js/src/test/tests.js:1328:36)

    at testMainClass.runStaticRequestTests (file:///home/travis/build/ccxt/ccxt/js/src/test/tests.js:1304:20)

    at testMainClass.init (file:///home/travis/build/ccxt/ccxt/js/src/test/tests.js:63:24)

    at file:///home/travis/build/ccxt/ccxt/js/src/test/tests.init.js:21:23

    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

    at process.<anonymous> (file:///home/travis/build/ccxt/ccxt/js/src/test/tests.helpers.js:19:11)

    at process.emit (node:events:514:28)

    at emit (node:internal/process/promises:149:20)

    at processPromiseRejections (node:internal/process/promises:283:27)

    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

    at process.<anonymous> (file:///home/travis/build/ccxt/ccxt/js/src/test/tests.helpers.js:11:11)

    at process.emit (node:events:514:28)

    at process._fatalException (node:internal/process/execution:149:25)
```

[ci skip]