Fix Error/Warning: A non-numeric value encountered
We Need to cast the vars as int else i got this error in a laravel command : 

Error: A non-numeric value encountered

And it's very anoying to debug because no line number is shown

Thanks