Update kucoin.py
myTrades = self.api_wrapper.fetch_my_trades(limit=300, params={param_key: param_value})
  File "/usr/local/lib/python3.7/dist-packages/ccxt/kucoin.py", line 816, in fetch_my_trades
    return self.parse_trades(trades, market, since, limit)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 1388, in parse_trades
    array = [self.parse_trade(trade, market) for trade in array]
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 1388, in <listcomp>
    array = [self.parse_trade(trade, market) for trade in array]
  File "/usr/local/lib/python3.7/dist-packages/ccxt/kucoin.py", line 946, in parse_trade
    'datetime': self.iso8601(timestamp),
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 848, in iso8601
    utc = datetime.datetime.utcfromtimestamp(timestamp // 1000)
ValueError: year 51354 is out of range