fix FTX endpoint latency stats
FTX endpoint latency stats is a private endpoint rather than a public endpoint.
I tested that the endpoint should work after moving to be under 'private'.
I updated ftx.js. Is there tests in this repo that I need to update as well?
Also I suppose other versions including ftx.py will be updated by CI bot.

See below error message for reference:

HTTPError: 401 Client Error: UNAUTHORIZED for url: https://ftx.com/api/stats/latency_stats
AuthenticationError: ftx {"success":false,"error":"Not logged in"}