package.json change npm test-base to use python3 instead of python
This allows
python/ccxt/test/test_decimal_to_precision.py and
python/ccxt/test/test_crypto.py
to pass.
When running with python (2), the following failure occurs:
root@af63df9e2453:/ccxt# python python/ccxt/test/test_decimal_to_precision.py
Traceback (most recent call last):
  File "python/ccxt/test/test_decimal_to_precision.py", line 14, in <module>
    from ccxt.base.decimal_to_precision import decimal_to_precision  # noqa F401
  File "/ccxt/python/ccxt/__init__.py", line 29, in <module>
    from ccxt.base.exchange import Exchange                     # noqa: F401
  File "/ccxt/python/ccxt/base/__init__.py", line 24, in <module>
    from ccxt.base import exchange
  File "/ccxt/python/ccxt/base/exchange.py", line 530
    def print(self, *args):
            ^
SyntaxError: invalid syntax
root@af63df9e2453:/ccxt# python3 python/ccxt/test/test_decimal_to_precision.py
root@af63df9e2453:/ccxt#