[FIX] kraken.py: fixing amount variable type convertion
Hello Community,

Problem appears when amount type 'str' compared with number 0 'int'.

Thanks

Traceback (most recent call last):
  File "kraken.py", line 27, in <module>
    trades = exchange.fetch_ledger(code=None, since=None, limit=None, params={'ofs': offset})
  File "/venv/lib/python3.8/site-packages/ccxt/kraken.py", line 958, in fetch_ledger
    return self.parse_ledger(items, currency, since, limit)
  File "/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 2574, in parse_ledger
    itemOrItems = self.parse_ledger_entry(arrayData[i], currency)
  File "/venv/lib/python3.8/site-packages/ccxt/kraken.py", line 891, in parse_ledger_entry
    if amount < 0:
TypeError: '<' not supported between instances of 'str' and 'int'