fix(bingx): add spotV1PrivateGetUserCommissionRate & spotV1PrivatePostTradeCancelOpenOrders to bingx abstract
receiving error error TS2339: Property "spotV1PrivatePostTradeCancelOpenOrders" does not exist on type "bingx". without this commit