feat(go): add Websockets(WS) support  (#26440)
* watchLiquidationsForSymbols, symbols is not optional

* moved piscina back to webworkerTranspile

* Revert "Reapply "renamed error to err""

This reverts commit 8de2c78355b500f9669321bd8612b92259cebe04.

* change safeGoName err to e

* Revert "watchMultiple, new exchange default values"

This reverts commit e1a55b068d1ee2d7663f51ce3e660cbf005a58aa.

* optionalArgs for orderbook reset and cache

* Describer

* added delta to goReservedWordsReplacement in safeGoName

* Revert "no variable named time, delta"

This reverts commit 111a361ea9a0b662dd7aaa53b1e1e1ca3e8d49eb.

* Revert "added delta to goReservedWordsReplacement in safeGoName"

This reverts commit d2bd66b7c6e280e66a4107c0f611a05dbaecf817.

* removed other unnecessary typescript changes

* removed error and timeVar from safeGoName

* add --ws transpilation

* fix createDynamicInstanceFile

* removed GetRootException(ex) transpilation

* Revert "ts array push separated to separate lines"

This reverts commit 6f4a4386bdbb3e4dbac19875cfb092d2ee426aac.

* cleanup

* handleErrorMessage return type, watchLiquidationsForSymbols unification

* unWatchPositions on exchange_interface

* websocket exchange_dynamic

* unify unWatchOrderBookForSymbols

* goTranspiler NewExchange fix

* removed transpiled changes

* ast-transpiler bump

* test-go

* fix kucoinfutures error, dynamic aliasExchanges

* Future.Resolve panic after ~30 seconds fix

* add protobuf placeholders

* add watchX support to CLI methods

* build go

* add build WS/

* transpile ws

* renamed ws to pro

* exchange_client onMessage messageStr conversion added back in

* fmt file

* add ws_metadata

* read decompress binary option

* init ws tests transpiling

* fix function

* test fixes

* watch tests compiling

* init arrayCache and OrderBook tests

* cache/ob tests compiling

* comment dead code

* add base-ws-go to pipeline

* equals working for cache

* fix arrayCacheByTimestamp

* more cache fixes (missing fixing getLimit)

* cache tests passing (missing orderbook tests

* orderboko tests working until indexed line 244

* indexed tests working

* counted ob tests passing

* base tests passing

* fix helper

* update command

* ws tests in go

* init ws exchange

* add [/stored\.\(ccxt\.Appender\)\.Append\(this.ParseOHLCV/g, stored.Append(this.ParseOHLCV], to go transpiler

* missing methods

* revert

* fix path

* Revert "revert"

This reverts commit c5b7ebed584ed148f92e8b52ccf0b00a69771463.

* cache path

* add proxy support

* missing file

* change getData type

* fix isArray

* wrap orderbook calls

* add unWrapType method

* double slash fix, semicolons

- fix double slash with → ./go/v4/pro//bitstamp_wrapper.go (createGoWrappers @ goTranspiler.ts:1353)
- paths in goTranspiler do not have trailing /
- add semicolons

* go orderbook.getIndexedAsksBids type cast fix

* fix: invalid memory address or nil pointer

fixes ```
> ccxt@4.5.1 cli.go
> go run -C go ./cli/main.go binanceusdm fetchMarkets

Exchange name:  binanceusdm
Method:  fetchMarkets
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104609f04]

goroutine 1 [running]:
github.com/ccxt/ccxt/go/v4.(*BinanceCore).Describe(0x0)
        /Users/caoilainn/Documents/programming/ccxt/go/v4/binance.go:19 +0x24
github.com/ccxt/ccxt/go/v4/pro.(*BinanceCore).Describe(0x1400028c940)
        /Users/caoilainn/Documents/programming/ccxt/go/v4/pro/binance.go:22 +0x24
github.com/ccxt/ccxt/go/v4/pro.(*BinanceusdmCore).Describe(0x1400028c930)
        /Users/caoilainn/Documents/programming/ccxt/go/v4/pro/binanceusdm.go:22 +0x24
github.com/ccxt/ccxt/go/v4/pro.(*BinanceusdmCore).Init(0x1400028c930, 0x1400029ee10)
        /Users/caoilainn/Documents/programming/ccxt/go/v4/pro/binanceusdm.go:47 +0x24
github.com/ccxt/ccxt/go/v4/pro.DynamicallyCreateInstance({0x16bbba844?, 0x1400023fef8?}, 0x1400029ee10)
        /Users/caoilainn/Documents/programming/ccxt/go/v4/pro/exchange_dynamic.go:40 +0x13c8
main.main()
        /Users/caoilainn/Documents/programming/ccxt/go/cli/main.go:483 +0xb24
exit status 2
```

* go props, default values, delay fix, clientInterface casting, setRateLimiter -> setEnableRateLimit

exchange prop types, default values, Delay method fix for int, cast as ClientInterface instead of WsClient and Client, SetRateLimit changed to SetEnableRateLimit because EnableRateLimit is the property that its setting and theres another prop called rateLimit which it doesnt set

* move init props statement

* fix python and c# builds

* minor change to GetsLimit regex in goTranspiler

* go: PanicOnError handle *Error type

* add arrayCache support to getValue and addElement

* add support to inOP

* fix spawn and verbose message

* try second version

* add granular go build script

* improve script

* fix watchBidsAsks related functions

* init ping pong fix

* fix rateLimit reading

* add lowercase version

* add lowercase version

* fix go build exchange_helpers

* skip nil values

* fix key casing

* fix slice bounds out of range error on exchange_orderbookside

* Revert "fix slice bounds out of range error on exchange_orderbookside"

This reverts commit f7d2b421957461315c7958ee087c539f7ed28bd8.

* add pong at the connection level

* handle simple str onMessage calls

* fix GetDescribeForExtendedWsExchange usecase

* apex ping fix

* fix transpiling

* other fixes

* fix apex modetrade and woofipro

* gunzip fix

* try to fix fatal error: concurrent map writes

* check if val is nul

* fix StoreArray array index issue

* fix exchange_helpers.go concurrent map writes

fatal error: concurrent map writes

goroutine 265 [running]:
internal/runtime/maps.fatal({0x10f961e10?, 0x10fad0b80?})
	/usr/local/Cellar/go/1.25.1/libexec/src/runtime/panic.go:1046 +0x18
github.com/ccxt/ccxt/go/v4.AddElementToObject({0x10fb08540?, 0xc0002228d0}, {0x10fad0940?, 0xc000aa3d20?}, {0x10fb2bf00, 0xc00061ef30})

* fix GetsLimit type error in WatchOHLCVForSymbols (string is not ccxt.GetsLimit)

fix by using ToGetsLimit instead of casting as GetsLimit

* set enableCompression to false

fixes: close 1006 (abnormal closure): unexpected EOF

* locks: this commit might be bad or unnecessary, i didnt want to push the other stuff without it though, revert if needed

* try to remove some data races

* lock sub

* check if connection is nil

* fix go version

* add some more locks

* tmp add toobit api to fix the build (why this is neccessary??)

* update emitAPI

* try disable test

* fix infinite loop in go tests

* Revert "fix StoreArray array index issue"

This reverts commit 5582402d61edf6df63897e132a2a23d2258bb0fe.

* fix keepALive parsing

* try without lock inside Await()

* revert

* OrderbookSide is no longer a pointer

* Revert "OrderbookSide is no longer a pointer"

This reverts commit 5c3f9d74b090d517d04584b63fd24c9785014545.

* go orderbookside getDataCopy

* go orderbookside getDataCopy

* build/granular-go-build.ts

* store array mutex locks

* use subscriber pattern instead

* prevent fix

* return immediately cached result

* add parseWsTrade to virtual base methods

* fix cache type and some helpers

* some fixes in loadOrderBook

* add getCacheIndex to derivedExchange

* parseWsTrade added to exchange_interface.go

With the edits in https://github.com/ccxt/ccxt/pull/26780/commits/0c326cb78f3fc3edc440aac78ff22ea080da42e8, when parseTradesHelper gets transpiled to go, there is an error that IDerivedExchange has no method ParseWsTrade

* removed simplify range expressionsimplifyrangedefault warning

for for i, _ := range currItem { in exchange_cache.go

* package.json transpileGORest and transpileGOWs commands

* removed nonce to Nonce transpilation

* fix average key error

* update test

* handle delta derived

* Revert "update test"

This reverts commit e650ab59c3a84e7f21b81813bfa2a1074df781f2.

* fix GetDataCopy

* delete only if symbol is available

* fix get array length

* Precise Reduce, String: int64 handling

* updated upbit markets and currenies

* add futures tests

* try to truncate stack

* fix lock

* link WS exchanges typed to rest typed

* restore missing changes from rebase

* Revert "link WS exchanges typed to rest typed"

This reverts commit f803f882581fc54459f7186d055288349e2cc898.

* update ts dev dependencies

* exchange_helpers.go removed TODOs for unnecessary nil checks

* fix typed alias wrappers

* reapply alias fixes

* update package-lock

* test.sharedMethods fix off by 1ms datetime errors

* fix datetimes off by 1ms error in tests

* revert unwanted changes

* emulate reusable future in GO to avoid auth reentrancy

* interface methods

* update spawn type

* add method to convert Ws ob to Rest

* go exchange_safe add safeVaue for orderbook when passed an int

* fix kucoinfutures error: Assertion failed: bids[0][0] (.*) should be < than asks[0][0] (.*)

* fix kucoin concurrent map writes error

* Revert "fix kucoinfutures error: Assertion failed: bids[0][0] (.*) should be < than asks[0][0] (.*)"

This reverts commit d35e1cc08e4fe883b91ae966e3bd65b05c551f70.

* bybit fix symbol should be assigned on orderbook error

* allow 1ms difference between datetime and timestamp off by a ms test

in go one of datetime/timestamp is truncated and the other is rounded so theyre off by 1ms sometimes

* update OB type

* try to fix close()

* wrap it in network error

* add testWsOrderBook

* add missing methods

* fix duplicated

* fix unWatch type

* go: fix unWatch with arrayCache

* go: fixed concurrent map writes

* update watchOHLCV

* revert changes

* add typed interface to ws and some examples

* fix cancelOrdersWs types

* update docs

* fix cancelOrdersWs type

* fix alias linking to typed wrapper

* tests: allow timestamp/datetime difference up to 500ms

* go pro types transpiled

* removed warning: should use a simple channel send/receive instead of select with a single case

* add test.structs

* go_wrapper_structs for pro are aliases that point to rest

* base exchange: add missing methods

* go_wrapper_structs for pro are aliases that point to rest

* base exchange: missing methods

* go_wrapper_structs for pro are aliases that point to rest

* fix trailing space

* add type test and update example

* add types rest types

---------

Co-authored-by: carlosmiei <43336371+carlosmiei@users.noreply.github.com>
Co-authored-by: Caoilainn <caoilainn@JIMs-Mac-mini.gateway.sasktel.net>